imports:
  - { resource: services.yaml }

services:

  _defaults:
    public: true

  test.App\Application\Contract\Transformer\ContractTransactionEntityTransformer: '@App\Application\Contract\Transformer\ContractTransactionEntityTransformer'
  test.App\Application\Contract\Transformer\ContractEntityTransformer: '@App\Application\Contract\Transformer\ContractEntityTransformer'
  test.App\Domain\ScContract\Service\ScContractResultBuilder: '@App\Domain\ScContract\Service\ScContractResultBuilder'
  test.App\Persistence\PersistorInterface: '@App\Persistence\PersistorInterface'
  test.App\Application\UserContract\Mapper\UserInvestmentTrxResultMapper: '@App\Application\UserContract\Mapper\UserInvestmentTrxResultMapper'
  test.App\Persistence\Token\TokenStorageInterface: '@App\Persistence\Token\TokenStorageInterface'
  test.App\Persistence\Contract\ContractStorageInterface: '@App\Persistence\Contract\ContractStorageInterface'
  test.App\Persistence\UserContract\UserContractStorageInterface: '@App\Persistence\UserContract\UserContractStorageInterface'
  test.App\Persistence\UserContract\UserContractPaymentStorageInterface: '@App\Persistence\UserContract\UserContractPaymentStorageInterface'
  test.App\Application\UserContract\Transformer\UserContractEntityTransformer: '@App\Application\UserContract\Transformer\UserContractEntityTransformer'
  test.App\Application\UserContract\Transformer\UserContractPaymentEntityTransformer: '@App\Application\UserContract\Transformer\UserContractPaymentEntityTransformer'
  test.App\Application\Contract\Mapper\GetContractBalanceMapper: '@App\Application\Contract\Mapper\GetContractBalanceMapper'
  test.App\Application\Contract\Transformer\ContractBalanceEntityTransformer: '@App\Application\Contract\Transformer\ContractBalanceEntityTransformer'
  test.App\Application\Contract\Transformer\ContractBalanceMovementTransformer: '@App\Application\Contract\Transformer\ContractBalanceMovementTransformer'

  test.App\Persistence\Contract\ContractBalanceMovementStorageInterface: '@App\Persistence\Contract\ContractBalanceMovementStorageInterface'
  test.App\Persistence\Contract\ContractBalanceStorageInterface: '@App\Persistence\Contract\ContractBalanceStorageInterface'
  test.App\Application\Contract\Transformer\ContractWithdrawalApprovalEntityTransformer: '@App\Application\Contract\Transformer\ContractWithdrawalApprovalEntityTransformer'
  test.App\Persistence\Contract\ContractWithdrawalApprovalStorageInterface: '@App\Persistence\Contract\ContractWithdrawalApprovalStorageInterface'

  test.App\Persistence\Contract\ContractReserveFundContributionStorageInterface: '@App\Persistence\Contract\ContractReserveFundContributionStorageInterface'
  test.App\Domain\Contract\Service\ContractReserveFundContributonIdEncoder: '@App\Domain\Contract\Service\ContractReserveFundContributonIdEncoder'
  test.App\Domain\Token\Service\TokenNormalizer: '@App\Domain\Token\Service\TokenNormalizer'
  test.App\Application\Contract\Service\ReceiveReserveFundContributionService: '@App\Application\Contract\Service\ReceiveReserveFundContributionService'
  test.App\Application\Contract\Transformer\ContractReserveFundContributionTransformer: '@App\Application\Contract\Transformer\ContractReserveFundContributionTransformer'
  test.App\Domain\Contract\Service\ContractMuxedIdGenerator: '@App\Domain\Contract\Service\ContractMuxedIdGenerator'

  test.App\Domain\Crypt\SecretBox\Service\Encryptor: '@App\Domain\Crypt\SecretBox\Service\Encryptor'
  test.App\Domain\Crypt\Aead\Service\AeadEncryptor: '@App\Domain\Crypt\Aead\Service\AeadEncryptor'
  test.App\Domain\Crypt\Aead\Service\EntityAeadEncryptor: '@App\Domain\Crypt\Aead\Service\EntityAeadEncryptor'  
